package com.example.demo.model.merchandise;

public enum MerchandiseCategory {
    CLEANING_SUPPLIES, GREENGROCER, BUTCHERS, GROCERY, PERSONAL_CARE, DAIRY_PRODUCTS, CEREALS, DRINKS, ALCOHOLIC_DRIKS,
    PET_STUFFS, BABY_CARE, BAKERY, FISH_STORE, FROZEN_FOOD, SWEET_AND_CANDY, NON_CLASSIFIED_PRODUCT ;
}
